# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-unit-test:

    runs-on: ubuntu-latest



    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js18
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Run npm install
      run: npm install
    - name: Run Unit Tests
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo "SimonaTafrova"
   
  build-and-ui-test:

    runs-on: ubuntu-latest



    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js18
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Run npm install
      run: npm install
    - name: Install playwright
      run: npx install playwright
    - name : Run IU tests
      run: npm run test:ui
    
